// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("❌ Supabase configuration error:", {
    url: supabaseUrl ? "✓ Present" : "✗ Missing",
    key: supabaseAnonKey ? "✓ Present" : "✗ Missing"
  });
  throw new Error(
    "Missing Supabase environment variables. Please check NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local"
  );
}

console.log("✅ Supabase client initializing with URL:", supabaseUrl);

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Test connection on initialization
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error("⚠️ Supabase auth connection test failed:", error);
  } else {
    console.log("✅ Supabase auth connection successful", {
      hasSession: !!data.session,
      userId: data.session?.user?.id
    });
  }
});
